CONTRIBUTING.md
addon/models/scope.js
addon/templates/scopes/index.hbs
package.json
tests/acceptance/scopes-test.js
tests/dummy/mirage/factories/scope.js
yarn.lock

feat: indent scopes list according to level

---

README.md
addon/components/data-table.js
addon/components/nav/item.hbs
addon/components/nav/item.js
addon/controllers/users/edit/index.js
addon/controllers/users/index.js
addon/engine.js
addon/services/emeis-options.js
addon/templates/scopes/edit.hbs
addon/templates/users/edit/index.hbs
addon/templates/users/index.hbs
app/services/emeis-options.js
config/environment.js
tests/acceptance/users-test.js
tests/dummy/app/app.js
tests/dummy/app/services/emeis-options.js
tests/dummy/config/environment.js
tests/unit/services/emeis-options-test.js
yarn.lock

- `emailAsUsername` can be used to hide the `username` field
- `additionalUserfields` can be used to specify which additional fields of the user model should be displayed
- `navigationEntries` can be used to specify which entries to show in main nav

feat: make addon configurable via config service

---

addon/controllers/scopes/edit.js
addon/models/scope.js
addon/templates/scopes/edit.hbs
tests/dummy/app/services/emeis-options.js

Meta fields can contain additional information on scopes and can be
passed by the `emeisOptions` service. The fields are customizable
in terms of readability and visibility.

feat(scopes): introduce meta fields

---

addon/components/meta-fields.hbs
addon/components/meta-fields.js
addon/controllers/scopes/edit/index.js
addon/controllers/users/edit/index.js
addon/templates/scopes/edit/index.hbs
addon/templates/users/edit/index.hbs
app/components/meta-fields.js
tests/dummy/app/services/emeis-options.js
tests/integration/components/meta-fields-test.js

Currently this will only allow metafields of type `text`

feat: extract meta fields rendering into a component

---

addon/components/data-table.hbs
addon/components/data-table.js
tests/integration/components/data-table-test.js
yarn.lock

we were using did-update on a getter before, which broke with a recent
update.

fix: data table paging

---

package.json

BREAKING CHANGE: drop support for node 10 as it has reached EOL.

chore: drop support for node 10

---

addon/components/data-table.hbs
addon/components/data-table.js

The search should take place over all entries and not only for the
ones on the current page.

fix(data-table): do not include page query param when searching

---

addon/components/tree.hbs
addon/controllers/scopes.js
addon/templates/scopes.hbs
app/styles/ember-emeis.scss

Fixes:
- selecting a tree-node while having `scopes->edit->acl`  tab active would change the view to `scopes->edit` instead
- tree-view is now wrapped by a scrollable container (larger lists of tree nodes)

fix: tree-node selection in acl tab, tree scroll container

---

README.md
addon/components/edit-form.hbs
tests/acceptance/data-table-test.js
tests/dummy/app/app.js
tests/integration/components/data-table-test.js
tests/integration/components/data-table/body-test.js
tests/integration/components/edit-form-test.js
tests/integration/helpers/indent-test.js
tests/unit/controllers/users/edit/acl-test.js

While testing there was a lot of noise in the console-output. This fixes most of them.
One crucial one is still open:

chore: fix a couple of cli warnings /deprecations

---

addon/components/data-table.hbs
addon/components/tree-node.hbs
addon/components/tree.hbs
addon/templates/application.hbs
addon/templates/scopes.hbs
app/styles/ember-emeis.scss

- adapt dynamic pane widths for tree view
- increase line-height for tree items
- set correct borders for the data-table search box

style: minor ui fixes tree search

---

README.md
addon/components/edit-form.hbs
addon/components/edit-form.js

It's not breaking the API, since we had no passed arguments to the callback function before, right? ;-)

fix(emeisOptions): include model in custom button callback

---

.github/workflows/test.yml
addon/components/meta-fields.hbs
addon/components/relationship-select.hbs
package.json
tests/dummy/mirage/config.js
tests/dummy/mirage/factories/acl.js
tests/dummy/mirage/factories/permission.js
tests/dummy/mirage/factories/role.js
tests/dummy/mirage/factories/scope.js
tests/dummy/mirage/factories/user.js
tests/dummy/mirage/identity-managers/slug.js
tests/dummy/mirage/identity-managers/uuid.js
tests/dummy/mirage/serializers/pagination.js
tests/integration/components/tree-node-test.js
yarn.lock

- substitutes `faker.js` with new `@faker/faker-js`
- change old imports from `ember-cli-mirage` to `miragejs`
- fix pipeline via resolutions for `@embroider/macros`

chore(deps): upgrade mirage

---

addon/components/data-table.hbs
addon/components/data-table/body.hbs
addon/templates/scopes/edit.hbs
addon/templates/users/edit.hbs
translations/de.yaml
translations/en.yaml

Not sure about the default wording of the warning when a user has no active ACL or a scope has no ACL.
> "This scope includes no permissions yet."

fix: special icon and info for empty acl list

---

addon/components/meta-fields.hbs
addon/components/meta-fields.js
addon/models/scope.js
addon/models/user.js
tests/dummy/mirage/factories/scope.js
tests/dummy/mirage/factories/user.js
tests/integration/components/meta-fields-test.js

Since django rest framework made this key a reserved attribute, we have to rename it for our usage.
More info [see here](https://github.com/projectcaluma/emeis/releases/tag/v1.0.0)
This change requires the emeis backend version >= 1.0.0
!BREAKING CHANGE

fix!: rename meta attribute to metainfo (django-rf change)

---

addon/components/acl-wizzard.hbs
addon/components/acl-wizzard/select-card.hbs
addon/components/edit-form.hbs
addon/components/tree-node.hbs
addon/templates/users/edit.hbs
addon/templates/users/index.hbs
package.json
yarn.lock

@czosel There is actually no breaking-change imho. We were on `ember-auto-import: ^2.4.0 ` already. So **no** new limitations to node-support.
The following should be of minor importance:
> ember-uikit v5 removed guaranteed support for all versions of Ember below version 3.24 LTS. It may still work, but there are no tests for it.
[Info from the migration guide](https://github.com/adfinis-sygroup/ember-uikit/blob/main/docs/migration-v5.md)

chore(deps): upgrade to ember-uikit v5

---

README.md
addon/models/localized.js
addon/templates/scopes/edit.hbs
tests/dummy/app/services/emeis-options.js

This makes the already existing override for field locales configurable
via the emeis-options service. The existing override on model level has
been removed, because it's not accessible when ember-emeis is used as an
engine.
The override is useful for cases when translations for specific models
are not required / wanted.

feat(emeis-options): add setting to force the locale of models

---

addon/controllers/users/index.js
addon/templates/users/edit.hbs
translations/de.yaml
translations/en.yaml

Because of the generic way `EditForm` is implemented, we currently show
a generic warning message when a user is deleted from the detail view.
This uses the same warning when a user is deleted from the list view
(for consistency).

fix(translations): consistent warning msg for user deletion

---

package.json
yarn.lock

This updates packages which had been depending on older embroider versions and now updated their deps. We can now safely delete our embroider resolutions.
Aside from that this includes some minor package updates.

chore(deps): clean embroider resolutions

---

addon/components/data-table.hbs

In the host app we use the yellow hover style as well.

fix: adapt table hover style

---

addon/components/tree-node.hbs
addon/templates/scopes/edit.hbs
addon/templates/users/edit.hbs
addon/templates/users/index.hbs
translations/de.yaml
translations/en.yaml

- adds an "inactive" badge to deactivated models (user/scope)
- stretch line-through styling across the all `<td>` elements of a deactivated user instead off only the first one (username)

style: improve inactive model stylez

---

addon/controllers/scopes.js

We only assert the route segment that we're sure of, making collisions
slightly more likely but still unlikely enough (hopefully).

fix: handle case where engine is mounted under different name

---

addon/components/tree-node.js
addon/components/tree.js
tests/integration/components/tree-node-test.js

...instead of item.id while passing filtered and expanded items.

Draft: fix(tree): consistent usage of referenced item

---

addon/components/tree.js
addon/controllers/scopes.js
addon/routes/scopes/new.js

In case of only one root element in the scopes list, searching for another entry didn't reveal child elements correctly.
This MR contains two fixes:
- fix the search for the scopes tree
- trigger a refresh of the scopes index (tree) when storing new scopes

fix: tree search expansion

---

README.md
addon/components/edit-form.hbs
addon/components/edit-form.js
addon/controllers/scopes/edit.js
addon/controllers/users/edit.js
package.json
tests/acceptance/users-test.js
tests/dummy/app/services/emeis-options.js
tests/integration/components/edit-form-test.js
yarn.lock

This MR refactors the `emeisOptions` and therefor lifts the model keys to the root of the config for better overview of the configuration.
Further it introduces *action button overrides* which are available like this:
```js
//config
user: {
actions: {
delete: {
label: "Override Label",
fn: (model) => model.id === 0,
}
}
}
```
If you only want to override the function as before, you can use `delete: (model) => model.id === 0` directly as before.

feat(emeisOptions): action button label overrides

---

addon/components/data-table.hbs

The search bar became to large with the release of the `filter-buttons` function. This PR corrects this behavior.

fix(data-table): fix search bar width

---

README.md
addon/controllers/users/edit.js
addon/templates/users/edit.hbs
tests/dummy/app/components/dummy-status/dummy-status.hbs
tests/dummy/app/components/dummy-status/dummy-status.js
tests/dummy/app/services/emeis-options.js

This adds a custom status component in the user detail view. It will be inline with the existing `inactive` badge on top of the form.

feat(emeis-options): custom user status component

---

addon/templates/users/edit.hbs

Previously phone numbers starting with `+` would get rejected. But the country code format is quite common.

fix(editForm): relax phone regex

---

addon/components/data-table.js

The `page` query param was missing and therefore no meta info was included in the response from the server, leading to a blank pagination status and a broken search behavior.
Reverts changes from https://github.com/projectcaluma/ember-emeis/pull/302

fix(data-table): always include page query param

---

package.json
yarn.lock

ember-cli-mirage was conflicting in floating dependency test with devDep for miragejs
Further includes a couple of patches.

chore(deps): resolve miragejs version conflict

---

README.md
addon/controllers/users/index.js
addon/helpers/evaluate-to-boolean.js
addon/templates/users/index.hbs
app/helpers/evaluate-to-boolean.js
tests/dummy/app/services/emeis-options.js
tests/integration/helpers/evaluate-to-boolean-test.js

Adds a new configuration option to `emeis-options` to hide the user list filter `active`/`inactive`.

feat(emeis-options): make user filter optionally visible

---

.eslintrc.js
.github/dependabot.yml
.github/workflows/release.yml
.github/workflows/test.yml
index.js
package.json
tests/acceptance/permissions-test.js
tests/acceptance/roles-test.js
tests/acceptance/scopes-test.js
tests/acceptance/users-test.js
tests/dummy/mirage/serializers/pagination.js
tests/helpers/assert-request.js
yarn.lock

Renaming of `@adfinis-sygroup` to `@adfinis/eslint-config` made the old package unavailable.
Upstream see here: https://github.com/adfinis/eslint-config/pull/336

chore(deps): update @adfinis/eslint-config and eslint

---

addon/components/edit-form.hbs
addon/components/tree.hbs
addon/templates/permissions/edit.hbs
addon/templates/users/edit.hbs
package.json
tests/acceptance/users-test.js
tests/integration/components/data-table-test.js
tests/integration/components/relationship-select-test.js
tests/unit/decorators/confirm-task-test.js
yarn.lock

The old [ember-simple-set-helper](https://github.com/pzuraq/ember-simple-set-helper) is outdated and should get replaced by [ember-set-helper](https://github.com/pzuraq/ember-set-helper).

refactor(ember-set-helper): replace deprecated ember-simple-set-helper

---

package.json
yarn.lock

`ember-uikit` drops ember `v3` support with this version!
We should merge this after  #625 is ready.

chore(deps): upgrade ember-uikit to v8
